### ISSUE TITLE
including FOSrest via symfony / composer

### ISSUE THREAD

**Issue by Gladhon** [FriendsOfSymfony/FOSRest#6]
Hi there

I try to install Fosrestbundle over composer.json

```
    "friendsofsymfony/rest-bundle": "dev-master",
```

and get an error from FOSRest:

  [UnexpectedValueException]  
  Invalid version string >=2.0.0

**Comment by lsmith77** [comment]
@Seldaek I guess i need to change this to `2.*` .. but why does this syntax work for the PHP requirement but not for Symfony?

**Comment by Seldaek** [comment]
`>=2.0.0` is a valid version constraint, but not a version itself. I'd guess the error came from somewhere else, but without seeing the complete composer.json, I can not say.

**Comment by Gladhon** [comment]
I found the only occurence of ">=2.0.0" in FOSrest over my complete project.

**Comment by Seldaek** [comment]
Well I can't reproduce here because of an assert bug (ping @naderman :|) in composer, so I'm unable to help at this point. Maybe later this weekend.

**Comment by mfoote** [comment]
Avatar thief!
